version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
  db:
    image: "postgres:11.6"
    ports:
      - "5432"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8070 -b '0.0.0.0'"
    volumes:
      - .:/guuzen
      - bundle:/bundle
    ports:
      - "8070:8070"
    links:
      - db
      - redis
    env_file: .env.development
    tty: true
    stdin_open: true
volumes:
  bundle:
    driver: local
